serviceAccount:
  name: karpenter
settings:
  clusterName: ops-eks-us-west-2-default
  clusterEndpoint: https://7B10E20BE328C6F4FEB31AF3B34E24C6.gr7.us-west-2.eks.amazonaws.com
  interruptionQueue: ops-default-karpenter
