serviceAccount:
  name: karpenter
settings:
  clusterName: oops-eks-us-west-1-kolya
  clusterEndpoint: https://B438FDC741987F1B1FAD07592EA853CD.gr7.us-west-1.eks.amazonaws.com
  interruptionQueue: oops-kolya-karpenter
