architecture: standalone
auth:
  enabled: false
master:
  nodeSelector:
    karpenter.sh/nodepool: common-nodepool
  persistence:
    enabled: true
    storageClass: gp3
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
metrics:
  enabled: false
