import * as fs from 'fs';
import * as path from 'path';

export interface KnowledgeFileEntry {
  fileName: string;
  title: string;
  description: string;
  relativePath: string;
}

/**
 * Scan knowledge/ directory for .md files, extract title and first paragraph
 * to build a Tier 1 index for CLAUDE.md and a Tier 2 index.md navigation file.
 *
 * Skips auto-generated files (glossary.md, accounts.md, index.md) and directories.
 */
export function scanKnowledgeFiles(knowledgeDir: string): KnowledgeFileEntry[] {
  if (!fs.existsSync(knowledgeDir)) return [];

  const autoGenerated = new Set(['glossary.md', 'accounts.md', 'index.md']);
  const entries: KnowledgeFileEntry[] = [];

  const files = fs.readdirSync(knowledgeDir).filter(
    f => f.endsWith('.md') && !autoGenerated.has(f) && !fs.statSync(path.join(knowledgeDir, f)).isDirectory(),
  );

  for (const fileName of files) {
    const filePath = path.join(knowledgeDir, fileName);
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split('\n');

    // Extract title from first # heading
    let title = fileName.replace('.md', '');
    for (const line of lines) {
      if (line.startsWith('# ')) {
        title = line.replace(/^#\s+/, '').trim();
        break;
      }
    }

    // Extract first non-empty, non-heading paragraph as description
    let description = '';
    let pastTitle = false;
    for (const line of lines) {
      if (line.startsWith('# ')) { pastTitle = true; continue; }
      if (!pastTitle) continue;
      if (line.startsWith('##')) continue;
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#') && !trimmed.startsWith('|') && !trimmed.startsWith('-') && !trimmed.startsWith('**')) {
        description = trimmed.length > 80 ? trimmed.substring(0, 77) + '...' : trimmed;
        break;
      }
    }

    entries.push({
      fileName,
      title,
      description,
      relativePath: `knowledge/${fileName}`,
    });
  }

  return entries.sort((a, b) => a.fileName.localeCompare(b.fileName));
}

/**
 * Generate Tier 1 index for CLAUDE.md — one line per file.
 */
export function generateKnowledgeIndex(entries: KnowledgeFileEntry[]): string | null {
  if (entries.length === 0) return null;

  const lines = [
    `遇到基础设施相关问题时，先查看以下知识文件，用 Read 读取相关文件获取详细信息：`,
    '',
  ];
  for (const e of entries) {
    const desc = e.description ? ` — ${e.description}` : '';
    lines.push(`- **${e.title}**${desc} → \`${e.relativePath}\``);
  }
  lines.push('');
  lines.push('详细导航见 `knowledge/index.md`。');
  return lines.join('\n');
}

/**
 * Generate Tier 2 index.md navigation file in knowledge/ directory.
 */
export function generateKnowledgeIndexFile(entries: KnowledgeFileEntry[], knowledgeDir: string): void {
  const lines = [
    '# Knowledge Base Index',
    '',
    '> 自动生成，请勿手动编辑。列出所有知识文件的标题、适用场景和路径。',
    '',
  ];

  // Group by prefix
  const runbooks = entries.filter(e => e.fileName.startsWith('runbook-'));
  const incidents = entries.filter(e => e.fileName.startsWith('incident-'));
  const others = entries.filter(e => !e.fileName.startsWith('runbook-') && !e.fileName.startsWith('incident-'));

  if (others.length > 0) {
    lines.push('## 基础知识');
    lines.push('');
    for (const e of others) {
      lines.push(`### ${e.title}`);
      lines.push(`- **文件**: \`${e.relativePath}\``);
      if (e.description) lines.push(`- **内容**: ${e.description}`);
      lines.push('');
    }
  }

  if (runbooks.length > 0) {
    lines.push('## Runbooks');
    lines.push('');
    for (const e of runbooks) {
      lines.push(`### ${e.title}`);
      lines.push(`- **文件**: \`${e.relativePath}\``);
      if (e.description) lines.push(`- **内容**: ${e.description}`);
      lines.push('');
    }
  }

  if (incidents.length > 0) {
    lines.push('## 事故记录');
    lines.push('');
    for (const e of incidents) {
      lines.push(`### ${e.title}`);
      lines.push(`- **文件**: \`${e.relativePath}\``);
      if (e.description) lines.push(`- **内容**: ${e.description}`);
      lines.push('');
    }
  }

  const indexPath = path.join(knowledgeDir, 'index.md');
  fs.writeFileSync(indexPath, lines.join('\n'), 'utf-8');
  console.log(`[knowledge-loader] Generated index.md (${entries.length} files)`);
}
