//! Ingest Mimir alertmanager notifications that carry SLO burn-rate labels
//! into the `slo_burn_events` table.
//!
//! This is a **read path from the existing alert pipeline** — no new webhook,
//! no new dedup strategy for incoming payloads. The flow is:
//!
//! 1. The webhook handler (`handlers/alerts.rs`) has already upserted an
//!    `issues` row for the alert.
//! 2. We inspect the alert's `labels` map. If it carries `slo_id`, we know
//!    the rule was generated by [`super::rule_generator`] and should be
//!    recorded as a burn event.
//! 3. On **firing**, insert a row into `slo_burn_events`. Flapping is
//!    suppressed by the partial UNIQUE index `uniq_slo_burn_open`
//!    (one open burn per `(slo_id, window)` pair) — `ON CONFLICT DO NOTHING`
//!    makes repeats a no-op.
//! 4. On **resolving**, flip `resolved_at` on the matching open row.
//!
//! Failures here must not fail the webhook — the alert pipeline owns the
//! primary source of truth (`issues`). We log and return `Ok(())` so the
//! HTTP handler keeps responding 200 OK.
//!
//! See `docs/platform-evolution.md` §4.4 and AGENT_BRIEF.md W4.

use crate::error::AppResult;
use crate::models::slo::{BURN_SEVERITY_PAGE, BURN_SEVERITY_TICKET};
use serde_json::Value;
use sqlx::PgPool;
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Label parsing
// ---------------------------------------------------------------------------

/// Parsed subset of an alert's label map that identifies a SLO burn event.
///
/// `slo_id` + `burn_window` are required; `severity` falls back to
/// `BURN_SEVERITY_TICKET` and `burn_multiplier` defaults to `0.0` if the
/// generator ever stops emitting those (we'd rather record the event than
/// drop it).
#[derive(Debug, Clone, PartialEq)]
pub struct SloBurnLabels {
    pub slo_id: Uuid,
    pub severity: String,
    pub window: String,
    pub burn_multiplier: f64,
}

/// Extract SLO burn labels from a Prometheus/Alertmanager `labels` object.
///
/// Returns `None` when the alert is not an SLO burn (no `slo_id` label, or
/// `slo_id` not parseable as a UUID). A return of `None` is **not** an
/// error — plenty of alerts flow through this ingestion path without being
/// SLO-labeled.
pub fn extract_slo_labels(labels: Option<&Value>) -> Option<SloBurnLabels> {
    let labels = labels?;
    let slo_id_str = labels.get("slo_id")?.as_str()?;
    let slo_id = Uuid::parse_str(slo_id_str).ok()?;

    let window = labels
        .get("burn_window")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();
    if window.is_empty() {
        // Without a window label we can't dedup on (slo_id, window) — skip.
        return None;
    }

    let severity = labels
        .get("severity")
        .and_then(|v| v.as_str())
        .map(normalize_burn_severity)
        .unwrap_or_else(|| BURN_SEVERITY_TICKET.to_string());

    let burn_multiplier = labels
        .get("burn_multiplier")
        .and_then(|v| {
            // The rule generator renders the multiplier as a YAML scalar
            // string (e.g. `"14.4"`); in some Alertmanager configs it may
            // round-trip as a JSON number. Accept both.
            v.as_str()
                .and_then(|s| s.parse::<f64>().ok())
                .or_else(|| v.as_f64())
        })
        .unwrap_or(0.0);

    Some(SloBurnLabels {
        slo_id,
        severity,
        window,
        burn_multiplier,
    })
}

/// Normalize arbitrary severity strings onto the schema enum. Mimir alerts
/// emit `page` / `ticket` directly (see `rule_generator`) but external
/// systems could feed in `critical` / `warning`; we map them the same way
/// [`crate::services::alerts::normalize_severity`] does for issues.
fn normalize_burn_severity(raw: &str) -> String {
    match raw.to_lowercase().as_str() {
        "page" | "critical" | "p1" => BURN_SEVERITY_PAGE.to_string(),
        _ => BURN_SEVERITY_TICKET.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Database writes
// ---------------------------------------------------------------------------

/// If the alert carries an `slo_id` label, record or close a burn event.
///
/// * `alert_labels` — the raw `labels` JSON blob off the alert payload.
/// * `is_resolved`  — `true` when the alert transitioned to "resolved".
/// * `issue_id`     — optional link to the just-created/updated `issues` row
///                    so the UI can jump from a burn event to its incident.
///
/// Returns `Ok(())` even on DB errors — we log and swallow so the caller
/// (the webhook handler) doesn't 500 on a secondary write. The primary
/// issue row is already committed; missing a burn event is recoverable.
pub async fn ingest_slo_burn_alert(
    pool: &PgPool,
    alert_labels: Option<&Value>,
    is_resolved: bool,
    issue_id: Option<Uuid>,
) -> AppResult<()> {
    let Some(burn) = extract_slo_labels(alert_labels) else {
        return Ok(());
    };

    if is_resolved {
        resolve_open_burn(pool, &burn).await;
    } else {
        insert_open_burn(pool, &burn, issue_id).await;
    }

    Ok(())
}

/// Insert a new open burn event. The partial unique index
/// `uniq_slo_burn_open` ensures that flapping or duplicate Alertmanager
/// retries collapse silently — `ON CONFLICT DO NOTHING` returns 0 rows
/// affected instead of an error.
async fn insert_open_burn(pool: &PgPool, burn: &SloBurnLabels, issue_id: Option<Uuid>) {
    // `threshold` is stored for audit but we don't have the objective_pct
    // here; record `burn_multiplier` and let readers compute the product if
    // needed. A follow-up can backfill from the SLO row; flagging as 0.0
    // means "threshold unknown at ingestion time".
    let result = sqlx::query(
        r#"INSERT INTO slo_burn_events
               (slo_id, severity, window, burn_rate, threshold, issue_id)
           VALUES ($1, $2, $3, $4, $5, $6)
           ON CONFLICT (slo_id, window) WHERE resolved_at IS NULL
               DO NOTHING"#,
    )
    .bind(burn.slo_id)
    .bind(&burn.severity)
    .bind(&burn.window)
    .bind(burn.burn_multiplier)
    .bind(0.0_f64)
    .bind(issue_id)
    .execute(pool)
    .await;

    match result {
        Ok(r) if r.rows_affected() > 0 => {
            tracing::info!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                severity = %burn.severity,
                "Recorded SLO burn event"
            );
        }
        Ok(_) => {
            tracing::debug!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                "Duplicate SLO burn suppressed (open event already exists)"
            );
        }
        Err(e) => {
            tracing::warn!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                error = %e,
                "Failed to insert SLO burn event"
            );
        }
    }
}

/// Close the matching open burn event for this (slo_id, window) pair.
/// If no row matches (e.g. we missed the firing edge), log at debug and
/// return — the resolve is idempotent.
async fn resolve_open_burn(pool: &PgPool, burn: &SloBurnLabels) {
    let result = sqlx::query(
        r#"UPDATE slo_burn_events
               SET resolved_at = NOW()
             WHERE slo_id = $1
               AND window = $2
               AND resolved_at IS NULL"#,
    )
    .bind(burn.slo_id)
    .bind(&burn.window)
    .execute(pool)
    .await;

    match result {
        Ok(r) if r.rows_affected() > 0 => {
            tracing::info!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                "Resolved SLO burn event"
            );
        }
        Ok(_) => {
            tracing::debug!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                "SLO burn resolve: no open event found"
            );
        }
        Err(e) => {
            tracing::warn!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                error = %e,
                "Failed to resolve SLO burn event"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
//
// DB-touching code paths are covered by integration tests in W7 — unit tests
// here focus on the label parser since it's the highest-risk bug surface
// (alertmanager payload shapes vary across provider and Mimir version).

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn extracts_all_fields_from_mimir_mwmbr_payload() {
        let labels = json!({
            "alertname": "SloBurnFast_7a3cbeef_Page1",
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "severity": "page",
            "burn_window": "1h",
            "burn_multiplier": "14.4"
        });
        let burn = extract_slo_labels(Some(&labels)).expect("should extract");
        assert_eq!(
            burn.slo_id,
            Uuid::parse_str("7a3cbeef-1234-4567-89ab-abcd12345678").unwrap()
        );
        assert_eq!(burn.severity, BURN_SEVERITY_PAGE);
        assert_eq!(burn.window, "1h");
        assert!((burn.burn_multiplier - 14.4).abs() < 1e-9);
    }

    #[test]
    fn accepts_numeric_burn_multiplier() {
        let labels = json!({
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "burn_window": "6h",
            "severity": "ticket",
            "burn_multiplier": 1.0
        });
        let burn = extract_slo_labels(Some(&labels)).expect("should extract");
        assert!((burn.burn_multiplier - 1.0).abs() < 1e-9);
    }

    #[test]
    fn defaults_severity_to_ticket_when_absent() {
        let labels = json!({
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "burn_window": "3d"
        });
        let burn = extract_slo_labels(Some(&labels)).expect("should extract");
        assert_eq!(burn.severity, BURN_SEVERITY_TICKET);
        assert_eq!(burn.burn_multiplier, 0.0);
    }

    #[test]
    fn non_slo_alert_returns_none() {
        let labels = json!({
            "alertname": "DiskFullWarning",
            "severity": "warning"
        });
        assert!(extract_slo_labels(Some(&labels)).is_none());
    }

    #[test]
    fn missing_labels_returns_none() {
        assert!(extract_slo_labels(None).is_none());
    }

    #[test]
    fn invalid_slo_id_returns_none() {
        let labels = json!({
            "slo_id": "not-a-uuid",
            "burn_window": "1h"
        });
        assert!(extract_slo_labels(Some(&labels)).is_none());
    }

    #[test]
    fn empty_burn_window_returns_none() {
        // Without a window we can't dedup — better to skip than corrupt.
        let labels = json!({
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "burn_window": ""
        });
        assert!(extract_slo_labels(Some(&labels)).is_none());
    }

    #[test]
    fn severity_normalizes_synonyms() {
        assert_eq!(normalize_burn_severity("page"), BURN_SEVERITY_PAGE);
        assert_eq!(normalize_burn_severity("PAGE"), BURN_SEVERITY_PAGE);
        assert_eq!(normalize_burn_severity("critical"), BURN_SEVERITY_PAGE);
        assert_eq!(normalize_burn_severity("P1"), BURN_SEVERITY_PAGE);
        assert_eq!(normalize_burn_severity("ticket"), BURN_SEVERITY_TICKET);
        assert_eq!(normalize_burn_severity("warning"), BURN_SEVERITY_TICKET);
        assert_eq!(normalize_burn_severity(""), BURN_SEVERITY_TICKET);
    }

    #[test]
    fn burn_multiplier_bad_string_falls_back_to_zero() {
        let labels = json!({
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "burn_window": "7d",
            "burn_multiplier": "not-a-number"
        });
        let burn = extract_slo_labels(Some(&labels)).expect("should extract");
        assert_eq!(burn.burn_multiplier, 0.0);
    }
}
