//! Ingest Mimir alertmanager notifications that carry SLO burn-rate labels
//! into the `slo_burn_events` table.
//!
//! This is a **read path from the existing alert pipeline** — no new webhook,
//! no new dedup strategy for incoming payloads. The flow is:
//!
//! 1. The webhook handler (`handlers/alerts.rs`) has already upserted an
//!    `issues` row for the alert.
//! 2. We inspect the alert's `labels` map. If it carries `slo_id`, we know
//!    the rule was generated by [`super::rule_generator`] and should be
//!    recorded as a burn event.
//! 3. On **firing**, insert a row into `slo_burn_events`. Flapping is
//!    suppressed by the partial UNIQUE index `uniq_slo_burn_open`
//!    (one open burn per `(slo_id, window)` pair) — `ON CONFLICT DO NOTHING`
//!    makes repeats a no-op.
//! 4. On **resolving**, flip `resolved_at` on the matching open row.
//!
//! Failures here must not fail the webhook — the alert pipeline owns the
//! primary source of truth (`issues`). We log and return `Ok(())` so the
//! HTTP handler keeps responding 200 OK.
//!
//! See `docs/platform-evolution.md` §4.4 and AGENT_BRIEF.md W4.

use crate::error::AppResult;
use crate::models::slo::{BURN_SEVERITY_PAGE, BURN_SEVERITY_TICKET};
use crate::services::incident::timeline_bus::TimelineBus;
use serde_json::Value;
use sqlx::PgPool;
use std::sync::{Arc, LazyLock};
use tokio::sync::Semaphore;
use uuid::Uuid;

/// Bound the number of concurrent page-severity promotions so an
/// alert-storm (many distinct SLOs firing page at once) can't spawn
/// hundreds of tokio tasks simultaneously, each of them holding a
/// DB connection and firing Slack/Jira HTTP requests. P1 #12.
///
/// 16 covers realistic burst patterns (dozens of services alerting
/// during a correlated region event) without saturating the Slack /
/// Jira rate-limit budget.
static PROMOTE_SEMAPHORE: LazyLock<Arc<Semaphore>> =
    LazyLock::new(|| Arc::new(Semaphore::new(16)));

// ---------------------------------------------------------------------------
// Label parsing
// ---------------------------------------------------------------------------

/// Parsed subset of an alert's label map that identifies a SLO burn event.
///
/// `slo_id` + `burn_window` are required; `severity` falls back to
/// `BURN_SEVERITY_TICKET` and `burn_multiplier` defaults to `0.0` if the
/// generator ever stops emitting those (we'd rather record the event than
/// drop it).
#[derive(Debug, Clone, PartialEq)]
pub struct SloBurnLabels {
    pub slo_id: Uuid,
    pub severity: String,
    pub window: String,
    pub burn_multiplier: f64,
}

/// Extract SLO burn labels from a Prometheus/Alertmanager `labels` object.
///
/// Returns `None` when the alert is not an SLO burn (no `slo_id` label, or
/// `slo_id` not parseable as a UUID). A return of `None` is **not** an
/// error — plenty of alerts flow through this ingestion path without being
/// SLO-labeled.
pub fn extract_slo_labels(labels: Option<&Value>) -> Option<SloBurnLabels> {
    let labels = labels?;
    let slo_id_str = labels.get("slo_id")?.as_str()?;
    let slo_id = Uuid::parse_str(slo_id_str).ok()?;

    let window = labels
        .get("burn_window")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();
    if window.is_empty() {
        // Without a window label we can't dedup on (slo_id, window) — skip.
        return None;
    }

    let severity = labels
        .get("severity")
        .and_then(|v| v.as_str())
        .map(normalize_burn_severity)
        .unwrap_or_else(|| BURN_SEVERITY_TICKET.to_string());

    let burn_multiplier = labels
        .get("burn_multiplier")
        .and_then(|v| {
            // The rule generator renders the multiplier as a YAML scalar
            // string (e.g. `"14.4"`); in some Alertmanager configs it may
            // round-trip as a JSON number. Accept both.
            v.as_str()
                .and_then(|s| s.parse::<f64>().ok())
                .or_else(|| v.as_f64())
        })
        .unwrap_or(0.0);

    Some(SloBurnLabels {
        slo_id,
        severity,
        window,
        burn_multiplier,
    })
}

/// Normalize arbitrary severity strings onto the schema enum. Mimir alerts
/// emit `page` / `ticket` directly (see `rule_generator`) but external
/// systems could feed in `critical` / `warning`; we map them the same way
/// [`crate::services::alerts::normalize_severity`] does for issues.
fn normalize_burn_severity(raw: &str) -> String {
    match raw.to_lowercase().as_str() {
        "page" | "critical" | "p1" => BURN_SEVERITY_PAGE.to_string(),
        _ => BURN_SEVERITY_TICKET.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Database writes
// ---------------------------------------------------------------------------

/// If the alert carries an `slo_id` label, record or close a burn event.
///
/// * `alert_labels` — the raw `labels` JSON blob off the alert payload.
/// * `is_resolved`  — `true` when the alert transitioned to "resolved".
/// * `issue_id`     — optional link to the just-created/updated `issues` row
///                    so the UI can jump from a burn event to its incident.
/// * `bus`          — shared `TimelineBus` so SSE subscribers get incident
///                    timeline events live when a page-severity burn
///                    auto-promotes to an incident. P1 #8.
///
/// Returns `Ok(())` even on DB errors — we log and swallow so the caller
/// (the webhook handler) doesn't 500 on a secondary write. The primary
/// issue row is already committed; missing a burn event is recoverable.
pub async fn ingest_slo_burn_alert(
    pool: &PgPool,
    bus: Arc<TimelineBus>,
    alert_labels: Option<&Value>,
    is_resolved: bool,
    issue_id: Option<Uuid>,
) -> AppResult<()> {
    let Some(burn) = extract_slo_labels(alert_labels) else {
        return Ok(());
    };

    if is_resolved {
        resolve_open_burn(pool, &burn).await;
    } else {
        insert_open_burn(pool, bus, &burn, issue_id).await;
    }

    Ok(())
}

/// Insert a new open burn event. The partial unique index
/// `uniq_slo_burn_open` ensures that flapping or duplicate Alertmanager
/// retries collapse silently — `ON CONFLICT DO NOTHING` returns 0 rows
/// affected instead of an error.
///
/// W10: on a successful (non-duplicate) insert we also:
///   1. Append a `change_events` row so the agent can correlate this burn
///      with non-incident deploy/config changes.
///   2. For `severity='page'` burns, auto-create an incident via the
///      standard `create_incident_with_automation` pipeline. A per-SLO
///      "last hour" dedup guard prevents a flapping alert from spawning
///      a herd of incidents.
async fn insert_open_burn(
    pool: &PgPool,
    bus: Arc<TimelineBus>,
    burn: &SloBurnLabels,
    issue_id: Option<Uuid>,
) {
    // `threshold` is stored for audit but we don't have the objective_pct
    // here; record `burn_multiplier` and let readers compute the product if
    // needed. A follow-up can backfill from the SLO row; flagging as 0.0
    // means "threshold unknown at ingestion time".
    let result = sqlx::query_scalar::<_, Uuid>(
        r#"INSERT INTO slo_burn_events
               (slo_id, severity, window, burn_rate, threshold, issue_id)
           VALUES ($1, $2, $3, $4, $5, $6)
           ON CONFLICT (slo_id, window) WHERE resolved_at IS NULL
               DO NOTHING
           RETURNING id"#,
    )
    .bind(burn.slo_id)
    .bind(&burn.severity)
    .bind(&burn.window)
    .bind(burn.burn_multiplier)
    .bind(0.0_f64)
    .bind(issue_id)
    .fetch_optional(pool)
    .await;

    match result {
        Ok(Some(burn_event_id)) => {
            tracing::info!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                severity = %burn.severity,
                "Recorded SLO burn event"
            );

            // Resolve SLO → (tenant_id, component_id, name) for both the
            // change_events row and the optional incident creation.
            let slo_ctx = fetch_slo_context(pool, burn.slo_id).await;

            // Always append to change_events, even for ticket-severity
            // burns: lower-priority burns are still useful context when
            // someone asks "what changed?" later.
            let summary = format!(
                "SLO {} burning at {:.1}x over {}",
                slo_ctx
                    .as_ref()
                    .map(|c| c.name.clone())
                    .unwrap_or_else(|| burn.slo_id.to_string()),
                burn.burn_multiplier,
                burn.window,
            );
            let actor = serde_json::json!({
                "type": "system",
                "display_name": "slo_engine",
                "source": "alert_ingestion",
            });
            let payload = serde_json::json!({
                "slo_id": burn.slo_id,
                "burn_window": burn.window,
                "burn_multiplier": burn.burn_multiplier,
                "severity": burn.severity,
                "issue_id": issue_id,
            });
            crate::services::change_events::record_best_effort(
                pool,
                slo_ctx.as_ref().and_then(|c| c.tenant_id),
                crate::models::change_event::KIND_SLO_BURN,
                slo_ctx.as_ref().and_then(|c| c.component_id),
                actor,
                summary.clone(),
                payload,
                crate::models::change_event::SOURCE_SLO_BURN,
                Some(burn_event_id.to_string()),
            )
            .await;

            // Only a `page` severity burn should promote to an incident.
            if burn.severity == crate::models::slo::BURN_SEVERITY_PAGE {
                spawn_incident_from_burn(pool, bus, burn, burn_event_id, issue_id, slo_ctx).await;
            }
        }
        Ok(None) => {
            tracing::debug!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                "Duplicate SLO burn suppressed (open event already exists)"
            );
        }
        Err(e) => {
            tracing::warn!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                error = %e,
                "Failed to insert SLO burn event"
            );
        }
    }
}

/// Convenience aggregate used by the W10 change_events / incident hookup.
#[derive(Debug, Clone)]
struct SloContext {
    name: String,
    tenant_id: Option<Uuid>,
    component_id: Option<Uuid>,
}

async fn fetch_slo_context(pool: &PgPool, slo_id: Uuid) -> Option<SloContext> {
    match sqlx::query_as::<_, (String, Uuid, Option<Uuid>)>(
        "SELECT name, tenant_id, component_id FROM slos WHERE id = $1",
    )
    .bind(slo_id)
    .fetch_optional(pool)
    .await
    {
        Ok(Some((name, tenant_id, component_id))) => Some(SloContext {
            name,
            tenant_id: Some(tenant_id),
            component_id,
        }),
        _ => None,
    }
}

/// For `page`-severity burns, spawn a background task that creates an
/// incident via the standard `create_incident_with_automation` pipeline —
/// same code path as a manual `POST /api/incidents`, so the war-room
/// automation (timeline seed + async Slack + async Jira) fires
/// automatically.
///
/// Dedup: if an incident tagged with this `slo_id` in its labels was
/// created in the last hour and is not yet closed, we skip. This prevents
/// a flapping alert from spawning a herd of incidents while still allowing
/// a legitimate re-fire once the previous one is closed.
async fn spawn_incident_from_burn(
    pool: &PgPool,
    bus: Arc<TimelineBus>,
    burn: &SloBurnLabels,
    burn_event_id: Uuid,
    source_issue_id: Option<Uuid>,
    slo_ctx: Option<SloContext>,
) {
    // Fire-and-forget dedup check + incident creation. The create path
    // itself already spawns its own background work; we just need to
    // detach the DB round-trips here so the webhook handler is not blocked.
    let pool_bg = pool.clone();
    let burn = burn.clone();
    let slo_ctx = slo_ctx.clone();
    tokio::spawn(async move {
        // Bound concurrent promotions (P1 #12). Acquiring the permit
        // happens inside the spawned task so the webhook handler is
        // never blocked on the semaphore.
        let _permit = match PROMOTE_SEMAPHORE.clone().acquire_owned().await {
            Ok(p) => p,
            Err(e) => {
                tracing::warn!(
                    slo_id = %burn.slo_id,
                    error = %e,
                    "SLO page burn: promote semaphore closed, skipping"
                );
                return;
            }
        };

        if should_skip_duplicate_incident(&pool_bg, burn.slo_id).await {
            tracing::info!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                "SLO page burn: recent active incident exists, skipping auto-incident"
            );
            return;
        }

        let affected = slo_ctx
            .as_ref()
            .and_then(|c| c.component_id)
            .map(|c| vec![c])
            .unwrap_or_default();
        let slo_name = slo_ctx
            .as_ref()
            .map(|c| c.name.clone())
            .unwrap_or_else(|| burn.slo_id.to_string());
        let tenant_id = slo_ctx.as_ref().and_then(|c| c.tenant_id);

        let req = crate::models::incident::CreateIncidentRequest {
            title: format!("SLO burn: {} at {:.1}x", slo_name, burn.burn_multiplier),
            severity: crate::models::incident::SEVERITY_SEV2.to_string(),
            status: None,
            detection_source: crate::models::incident::DETECTION_SOURCE_SLO_BURN.to_string(),
            impact_summary: Some(format!(
                "Error budget burning at {:.1}x over {} window",
                burn.burn_multiplier, burn.window
            )),
            affected_component_ids: affected,
            affected_customer_tier: None,
            source_issue_id,
            started_at: chrono::Utc::now(),
            commander_user_id: None,
            scribe_user_id: None,
            bridge_url: None,
            labels: Some(serde_json::json!({
                "slo_id": burn.slo_id,
                "burn_window": burn.window,
                "burn_multiplier": burn.burn_multiplier,
            })),
            tenant_id,
        };

        // P1 #8: the real, shared TimelineBus threads in from AppState so
        // SSE subscribers on /api/incidents/:id/timeline/stream receive the
        // auto-created incident's seed event live. Previously this spot
        // built a throwaway bus, which meant auto-incident timeline events
        // never fanned out to connected clients.
        if let Err(e) = crate::services::incident::lifecycle::create_incident_with_automation(
            &pool_bg,
            bus,
            tenant_id,
            crate::services::incident::lifecycle::IncidentSource::SloBurn {
                slo_burn_event_id: burn_event_id,
            },
            req,
        )
        .await
        {
            tracing::warn!(
                slo_id = %burn.slo_id,
                error = %e,
                "SLO page burn: auto-incident creation failed"
            );
        }
    });
}

/// Dedup guard: `true` if an incident tagged with this SLO id was created
/// within the last hour and is not yet closed. See `should_skip_for_slo`
/// for the pure-logic test fixture covering this rule.
async fn should_skip_duplicate_incident(pool: &PgPool, slo_id: Uuid) -> bool {
    match sqlx::query_scalar::<_, bool>(
        r#"SELECT EXISTS(
               SELECT 1 FROM incidents
               WHERE labels->>'slo_id' = $1
                 AND status <> 'closed'
                 AND created_at > NOW() - interval '1 hour'
           )"#,
    )
    .bind(slo_id.to_string())
    .fetch_one(pool)
    .await
    {
        Ok(v) => v,
        Err(e) => {
            // Fail closed (P1 #12): if the dedup query errors we can't tell
            // whether a recent incident already exists. A DB hiccup during
            // an alert storm would otherwise let every duplicate page
            // create its own incident. Skipping on error costs at most one
            // delayed page-promotion until the webhook re-fires; it
            // prevents an incident herd.
            tracing::warn!(
                slo_id = %slo_id,
                error = %e,
                "SLO page burn: dedup check failed, skipping auto-incident (fail-closed)"
            );
            true
        }
    }
}

/// Pure-logic variant of [`should_skip_duplicate_incident`] used in unit
/// tests. Given the most recent incident row that labels this SLO, decide
/// whether a new page-burn should be suppressed. Kept separate so the test
/// matrix can run without a Postgres pool.
#[cfg(test)]
fn should_skip_for_slo_row(
    now: chrono::DateTime<chrono::Utc>,
    most_recent_for_slo: Option<(chrono::DateTime<chrono::Utc>, &str)>,
) -> bool {
    match most_recent_for_slo {
        Some((created_at, status)) if status != "closed" => {
            now.signed_duration_since(created_at).num_seconds() < 3600
        }
        _ => false,
    }
}

/// Close the matching open burn event for this (slo_id, window) pair.
/// If no row matches (e.g. we missed the firing edge), log at debug and
/// return — the resolve is idempotent.
async fn resolve_open_burn(pool: &PgPool, burn: &SloBurnLabels) {
    let result = sqlx::query(
        r#"UPDATE slo_burn_events
               SET resolved_at = NOW()
             WHERE slo_id = $1
               AND window = $2
               AND resolved_at IS NULL"#,
    )
    .bind(burn.slo_id)
    .bind(&burn.window)
    .execute(pool)
    .await;

    match result {
        Ok(r) if r.rows_affected() > 0 => {
            tracing::info!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                "Resolved SLO burn event"
            );
        }
        Ok(_) => {
            tracing::debug!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                "SLO burn resolve: no open event found"
            );
        }
        Err(e) => {
            tracing::warn!(
                slo_id = %burn.slo_id,
                window = %burn.window,
                error = %e,
                "Failed to resolve SLO burn event"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
//
// DB-touching code paths are covered by integration tests in W7 — unit tests
// here focus on the label parser since it's the highest-risk bug surface
// (alertmanager payload shapes vary across provider and Mimir version).

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn extracts_all_fields_from_mimir_mwmbr_payload() {
        let labels = json!({
            "alertname": "SloBurnFast_7a3cbeef_Page1",
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "severity": "page",
            "burn_window": "1h",
            "burn_multiplier": "14.4"
        });
        let burn = extract_slo_labels(Some(&labels)).expect("should extract");
        assert_eq!(
            burn.slo_id,
            Uuid::parse_str("7a3cbeef-1234-4567-89ab-abcd12345678").unwrap()
        );
        assert_eq!(burn.severity, BURN_SEVERITY_PAGE);
        assert_eq!(burn.window, "1h");
        assert!((burn.burn_multiplier - 14.4).abs() < 1e-9);
    }

    #[test]
    fn accepts_numeric_burn_multiplier() {
        let labels = json!({
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "burn_window": "6h",
            "severity": "ticket",
            "burn_multiplier": 1.0
        });
        let burn = extract_slo_labels(Some(&labels)).expect("should extract");
        assert!((burn.burn_multiplier - 1.0).abs() < 1e-9);
    }

    #[test]
    fn defaults_severity_to_ticket_when_absent() {
        let labels = json!({
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "burn_window": "3d"
        });
        let burn = extract_slo_labels(Some(&labels)).expect("should extract");
        assert_eq!(burn.severity, BURN_SEVERITY_TICKET);
        assert_eq!(burn.burn_multiplier, 0.0);
    }

    #[test]
    fn non_slo_alert_returns_none() {
        let labels = json!({
            "alertname": "DiskFullWarning",
            "severity": "warning"
        });
        assert!(extract_slo_labels(Some(&labels)).is_none());
    }

    #[test]
    fn missing_labels_returns_none() {
        assert!(extract_slo_labels(None).is_none());
    }

    #[test]
    fn invalid_slo_id_returns_none() {
        let labels = json!({
            "slo_id": "not-a-uuid",
            "burn_window": "1h"
        });
        assert!(extract_slo_labels(Some(&labels)).is_none());
    }

    #[test]
    fn empty_burn_window_returns_none() {
        // Without a window we can't dedup — better to skip than corrupt.
        let labels = json!({
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "burn_window": ""
        });
        assert!(extract_slo_labels(Some(&labels)).is_none());
    }

    #[test]
    fn severity_normalizes_synonyms() {
        assert_eq!(normalize_burn_severity("page"), BURN_SEVERITY_PAGE);
        assert_eq!(normalize_burn_severity("PAGE"), BURN_SEVERITY_PAGE);
        assert_eq!(normalize_burn_severity("critical"), BURN_SEVERITY_PAGE);
        assert_eq!(normalize_burn_severity("P1"), BURN_SEVERITY_PAGE);
        assert_eq!(normalize_burn_severity("ticket"), BURN_SEVERITY_TICKET);
        assert_eq!(normalize_burn_severity("warning"), BURN_SEVERITY_TICKET);
        assert_eq!(normalize_burn_severity(""), BURN_SEVERITY_TICKET);
    }

    #[test]
    fn burn_multiplier_bad_string_falls_back_to_zero() {
        let labels = json!({
            "slo_id": "7a3cbeef-1234-4567-89ab-abcd12345678",
            "burn_window": "7d",
            "burn_multiplier": "not-a-number"
        });
        let burn = extract_slo_labels(Some(&labels)).expect("should extract");
        assert_eq!(burn.burn_multiplier, 0.0);
    }

    // ------------------------------------------------------------------
    // W10 dedup-rule unit tests — pure logic covering
    // `should_skip_for_slo_row`. The DB variant is exercised via
    // integration tests; here we pin the decision matrix.
    // ------------------------------------------------------------------
    use chrono::{Duration, Utc};

    #[test]
    fn dedup_skips_when_recent_active_incident_exists() {
        let now = Utc::now();
        let recent_open = Some((now - Duration::minutes(10), "investigating"));
        assert!(
            should_skip_for_slo_row(now, recent_open),
            "recent active incident must suppress the auto-create path"
        );
    }

    #[test]
    fn dedup_proceeds_when_no_prior_incident() {
        let now = Utc::now();
        assert!(
            !should_skip_for_slo_row(now, None),
            "no prior incident means we must create one"
        );
    }

    #[test]
    fn dedup_proceeds_when_prior_incident_is_closed() {
        let now = Utc::now();
        let closed_recent = Some((now - Duration::minutes(10), "closed"));
        assert!(
            !should_skip_for_slo_row(now, closed_recent),
            "closed incidents must not block a re-fire"
        );
    }

    #[test]
    fn dedup_proceeds_when_prior_incident_is_older_than_one_hour() {
        let now = Utc::now();
        let stale_open = Some((now - Duration::minutes(61), "mitigated"));
        assert!(
            !should_skip_for_slo_row(now, stale_open),
            "incidents older than 1h must not block a re-fire"
        );
    }

    #[test]
    fn dedup_skips_exactly_under_one_hour_boundary() {
        let now = Utc::now();
        // 59m59s → still within the 1h window → skip.
        let under = Some((now - Duration::seconds(3599), "acknowledged"));
        assert!(should_skip_for_slo_row(now, under));
    }
}
