apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: common-nodeclass
spec:
  role: "${node_iam_role_name}"
  amiFamily: AL2023
  amiSelectorTerms:
    - name: amazon-eks-node-al2023-*
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 30Gi
        volumeType: gp3
        iops: 6000
        encrypted: false
        deleteOnTermination: true
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${subnetSelectorTermsValue}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${subnetSelectorTermsValue}
  tags:
    karpenter.sh/discovery: ${subnetSelectorTermsValue}
